# GNU Make solution makefile autogenerated by Premake
# Usage: make [ config=config_name ]
# Where {config_name} is one of: "debug", "release", "debug32", "release32", "debug64", "release64".

ifndef config
  config=debug
endif
export config

PROJECTS := unibot

.PHONY: all clean $(PROJECTS)

all: $(PROJECTS)

unibot: 
	@echo ==== Building unibot ====
	@${MAKE} --no-print-directory -C . -f unibot.make

clean:
	@${MAKE} --no-print-directory -C . -f unibot.make clean

