dofile 42.lua
dofile bindings_test.lua
dofile cmd.lua
dofile dict.lua
dofile env.lua
dofile g.lua
dofile happa.lua
dofile help.lua
dofile kick.lua
dofile mensa.lua
dofile paste.lua
dofile ping.lua
dofile roulette.lua
dofile spec.lua
dofile ss10.lua
dofile system.lua
dofile time.lua
dofile unikram.lua
dofile upload.lua
dofile wa.lua
dofile wd.lua
dofile we.lua
dofile who_is_your_daddy.lua
dofile ws0910.lua
